WebApp.WEB/Controllers/GuestController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestSharp;
using WebApp.WEB.Filter;
using WEBApp.DataAccess.Models;
using WEBApp.ViewModels;
using WebApp.WEB.Models.Account;
using WEBApp.Helpers;

namespace WebApp.WEB.Controllers
{
    public class GuestController : Controller
    {
        private readonly ILogger<GuestController> _logger;
        private readonly IConfiguration _configuration;
        public GuestController(ILogger<GuestController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
        }

        [AuthorizationPrivilageFilter]
        public IActionResult Index()
        {
            return View();
        }

        [AuthorizationPrivilageFilter]
        [HttpPost]
        public IActionResult GetAllTamu(IFormCollection collection)
        {
            var data = new DataTablesParameters
            {
                Draw = Convert.ToInt32(collection["draw"].FirstOrDefault()),
                Start = Convert.ToInt32(collection["start"].FirstOrDefault()),
                Length = Convert.ToInt32(collection["length"].FirstOrDefault()),
                SearchValue = collection["search[value]"].FirstOrDefault(),
                sortColumn = collection["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault(),
                sortColumnDirection = collection["order[0][dir]"].FirstOrDefault()
            };
            var json = JsonConvert.SerializeObject(data);
            var endpoint = _configuration.GetSection("ApiUrl").Value + "/Guest/GetAll";
            var jsonViewModel = new GridViewModel<List<TamuViewModel>>();
            var jsonData = new { draw = 0, recordsFiltered = 0, recordsTotal = 0, data = jsonViewModel.Data, isSuccess = false };
            try
            {
                jsonViewModel = RestAPIHelper<GridViewModel<List<TamuViewModel>>>.Submit(json, Method.POST, endpoint, Request);
                jsonData = new { draw = jsonViewModel.Draw, recordsFiltered = jsonViewModel.RecordsTotal, recordsTotal = jsonViewModel.RecordsTotal, data = jsonViewModel.Data, isSuccess = true };
            }
            catch (Exception e)
            {
                if (e.Message == "UnAuthorize")
                {
                    jsonData = new { draw = 0, recordsFiltered = 0, recordsTotal = 0, data = jsonViewModel.Data, isSuccess = false };
                }
            }
            return Json(jsonData);

        }
        [AuthorizationPrivilageFilter]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateGuestViewModel collection)
        {
            var endpoint = _configuration.GetSection("ApiUrl").Value + "/Guest/Create";
            var ajaxViewModel = new AjaxViewModel<string>();
            var json = JsonConvert.SerializeObject(collection);
            try
            {
                ajaxViewModel = RestAPIHelper<AjaxViewModel<string>>.Submit(json, Method.POST, endpoint,Request);
                if (ajaxViewModel.IsSuccess)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Create");
                }

            }
            catch (Exception e)
            {
                return RedirectToAction("Create");
            }
        }

        [AuthorizationPrivilageFilter]
        [HttpPost]
        public IActionResult DeleteTamu(int id)
        {
            var endpoint = _configuration.GetSection("ApiUrl").Value + "/Guest/Delete?id=" + id;
            var jsonViewModel = new AjaxViewModel<string>();
            var jsonData = new { isSuccess = false };
            try
            {
                jsonViewModel = RestAPIHelper<AjaxViewModel<string>>.Submit("", Method.POST, endpoint, Request);
                jsonData = new { isSuccess = true };
            }
            catch (Exception e)
            {
                if (e.Message == "UnAuthorize")
                {
                    jsonData = new { isSuccess = false };
                }
            }
            return Json(jsonData);

        }
        [AuthorizationPrivilageFilter]
        public IActionResult Edit(int id)
        {
            var endpoint = _configuration.GetSection("ApiUrl").Value + "/Guest/GetById?id=" + id;
            var jsonViewModel = new AjaxViewModel<CreateGuestViewModel>();
            try
            {
                jsonViewModel = RestAPIHelper<AjaxViewModel<CreateGuestViewModel>>.Submit("", Method.GET, endpoint, Request);
                
            }
            catch (Exception e)
            {
                if (e.Message == "UnAuthorize")
                {
                    
                    return RedirectToAction("Login","Account");
                }
            }
            return View(jsonViewModel.Data);

        }
        [HttpPost]
        public IActionResult Update(CreateGuestViewModel collection)
        {
            var endpoint = _configuration.GetSection("ApiUrl").Value + "/Guest/Update";
            var ajaxViewModel = new AjaxViewModel<string>();
            var json = JsonConvert.SerializeObject(collection);
            try
            {
                ajaxViewModel = RestAPIHelper<AjaxViewModel<string>>.Submit(json, Method.POST, endpoint, Request);
                if (ajaxViewModel.IsSuccess)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Edit");
                }

            }
            catch (Exception e)
            {
                return RedirectToAction("Create");
            }
        }
    }
}

WebApp.WEB/Views/Guest/Create.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <h1>Create Guest</h1>
    </div>
    @using (Html.BeginForm("Create", "Guest", FormMethod.Post, new { @class = "" }))
    {
        <div class="row">
            <div class="col-md-12">
                <label for="NomorRegister" class="form-label"><b>Nomor Register</b></label>
                <input class="form-control" type="text" name="NomorRegister" id="NomorRegister" required>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label for="NamaDepan" class="form-label"><b>Nama Depan</b></label>
                <input class="form-control" type="text" name="NamaDepan" id="NamaDepan" required>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label for="NamaBelakang" class="form-label"><b>Nama Belakang</b></label>
                <input class="form-control" type="text" name="NamaBelakang" id="NamaBelakang" required>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label for="TanggalLahir" class="form-label"><b>Tanggal Lahir</b></label>
                <input class="form-control" type="date" name="TanggalLahir" id="TanggalLahir" required>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label for="TempatLahir" class="form-label"><b>Tempat Lahir</b></label>
                <input class="form-control" type="text" name="TempatLahir" id="TempatLahir" required>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label for="NomorKTP" class="form-label"><b>Nomor KTP</b></label>
                <input class="form-control" type="text" name="NomorKTP" id="NomorKTP" required>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="JenisKelamin">Jenis Kelamin</label>
                    <select class="form-control" id="JenisKelamin" name="JenisKelamin">
                        <option value="1">Laki - Laki</option>
                        <option value="2">Perempuan</option>
                    </select>
                </div>
            </div>
        </div>
        
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-12">
                <button type="submit" class="btn btn-outline-primary">SAVE</button>
            </div>
        </div>

    }
</div>

WebApp.WEB/Views/Guest/Edit.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model WEBApp.ViewModels.CreateGuestViewModel
<div class="container">
    <div class="row">
        <h1>Create Guest</h1>
    </div>
    @using (Html.BeginForm("Update", "Guest", FormMethod.Post))
    {
        <input class="form-control" type="hidden" name="Id" id="Id" value="@Model.Id" required>

        <div class="row">
            <div class="col-md-12">
                <label for="NomorRegister" class="form-label"><b>Nomor Register</b></label>
                <input class="form-control" type="text" name="NomorRegister" id="NomorRegister" value="@Model.NomorRegister" required>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label for="NamaDepan" class="form-label"><b>Nama Depan</b></label>
                <input class="form-control" type="text" name="NamaDepan" id="NamaDepan" value="@Model.NamaDepan" required>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label for="NamaBelakang" class="form-label"><b>Nama Belakang</b></label>
                <input class="form-control" type="text" name="NamaBelakang" id="NamaBelakang" value="@Model.NamaBelakang" required>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label for="TanggalLahir" class="form-label"><b>Tanggal Lahir</b></label>
                <input class="form-control" type="date" name="TanggalLahir" id="TanggalLahir" value="@Model.TanggalLahir?.ToString("yyyy-MM-dd")" required>

            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label for="TempatLahir" class="form-label"><b>Tempat Lahir</b></label>
                <input class="form-control" type="text" name="TempatLahir" id="TempatLahir" value="@Model.TempatLahir" required>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label for="NomorKTP" class="form-label"><b>Nomor KTP</b></label>
                <input class="form-control" type="text" name="NomorKTP" id="NomorKTP" value="@Model.NomorKTP" required>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="JenisKelamin">Jenis Kelamin</label>
                    @Html.DropDownList("JenisKelamin", new List<SelectListItem>
                    {
                    new SelectListItem { Text = "Laki - Laki", Value = "1" },
                    new SelectListItem { Text = "Perempuan", Value = "2" },
                    new SelectListItem { Text = "Lainnya", Value = "3" }
                    }, new { @class = "form-control" })

                </div>
            </div>
        </div>

        <div class="row" style="margin-top: 10px;">
            <div class="col-md-12">
                <button type="submit" class="btn btn-outline-primary">SAVE</button>
            </div>
        </div>

    }
</div>

WebApp.WEB/Views/Guest/Index.cshtml
@{
    ViewData["Title"] = "List Tamu";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>List Tamu</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
           <a class="btn btn-primary" asp-controller="Guest" asp-action="Create">ADD</a>
        </div>
    </div>
    <div class="row" style="margin-top:10px;">
        <div class="col-md-12">
            <table id="example" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nomor Register</th>
                        <th>Nama Depan</th>
                        <th>Nama Belakang</th>
                        <th>Tanggal Lahir</th>
                        <th>Tempat Lahir</th>
                        <th>Jenis Kelaminr</th>
                        <th>NO KTP</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Nomor Register</th>
                        <th>Nama Depan</th>
                        <th>Nama Belakang</th>
                        <th>Tanggal Lahir</th>
                        <th>Tempat Lahir</th>
                        <th>Jenis Kelaminr</th>
                        <th>NO KTP</th>
                        <th></th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@section Scripts
{
    <script src="~/js/Tamu.js"></script>
}